version: "3"
services:

  nginx:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443

  backend:
    build: .
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 4000"
    ports:
      - 4000:4000
